<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpatialCircuits.Cells\SpatialCircuits.Cells.csproj" />
    <ProjectReference Include="..\SpatialCircuits.Core\SpatialCircuits.Core.csproj" />
    <ProjectReference Include="..\SpatialCircuits.Hierarchy\SpatialCircuits.Hierarchy.csproj" />
    <ProjectReference Include="..\SpatialCircuits.Persistence\SpatialCircuits.Persistence.csproj" />
  </ItemGroup>
</Project>
