<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SpatialCircuits.Benchmarks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\SpatialCircuits.Cells\SpatialCircuits.Cells.csproj" />
    <ProjectReference Include="..\src\SpatialCircuits.Persistence\SpatialCircuits.Persistence.csproj" />
    <ProjectReference Include="..\src\SpatialCircuits.Runner\SpatialCircuits.Runner.csproj" />
  </ItemGroup>
</Project>
